// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Guild struct {
	ID               int64
	PermissionRoleID sql.NullInt64
	EpicenterRoleID  sql.NullInt64
	LuckRoleID       sql.NullInt64
	PvpNaRoleID      sql.NullInt64
	PvpEuRoleID      sql.NullInt64
	PvpAsRoleID      sql.NullInt64
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}
