// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Guild struct {
	ID               int64
	PermissionRoleID sql.NullInt64
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type PingConfig struct {
	ID             int64
	GuildID        int64
	Name           string
	Description    sql.NullString
	RequiredRoleID sql.NullInt64
	TargetRoleID   int64
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}
